[package]
name = "fasthash"
version = "0.1.0"
authors = ["Matthew MacLeod <matt@umm.io>"]

[dependencies]
rustc-serialize = "0.3.0"
libc = "*"
postgres = "0.11"

[lib]
name = "fasthash"
crate_type = ["staticlib", "dylib"]
